version: "3"
services:
  web:
    container_name: "shopinsApi"
    build: .
    ports: 
      - 3000:3000
    depends_on:
      - db
    volumes: 
      - .:/usr/src/app/
    command: npm run start:dev
  db: 
    container_name: "mssql_database"
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    ports:
      - 1433:1433
    environment: 
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes: 
      - sqlvolumes:/var/opt/mssql
volumes:
  sqlvolumes:
